### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by tar-xzvff** [tar-xzvff/terraform-manager#27]
Traceback (most recent call last):
  File "/terraform-manager/terraform_manager/common/common_tasks.py", line 219, in direct_apply
    return_code, stdout, stderr = tf.apply(var=var)
  File "/usr/local/lib/python3.5/dist-packages/python_terraform/__init__.py", line 103, in apply
    return self.cmd('apply', *args, **option_dict)
  File "/usr/local/lib/python3.5/dist-packages/python_terraform/__init__.py", line 282, in cmd
    self.read_state_file()
  File "/usr/local/lib/python3.5/dist-packages/python_terraform/__init__.py", line 332, in read_state_file
    self.tfstate = Tfstate.load_file(file_path)
  File "/usr/local/lib/python3.5/dist-packages/python_terraform/tfstate.py", line 26, in load_file
    json_data = json.load(f)
  File "/usr/lib/python3.5/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 608: ordinal not in range(128)

**Comment by tar-xzvff** [comment]
#29 にて対応
